2021-08-07 23:52:18,054-ERROR:py36:用例失败assert 0 == 1-test_register.py-line19
2021-08-07 23:52:28,133-ERROR:py36:用例失败assert 0 == 1-test_register.py-line19
2021-08-08 15:48:10,540-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:10,736-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:10,840-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:10,962-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,084-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,206-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,326-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,468-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,598-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 15:48:11,718-ERROR:py36:用例失败assert 0 == 1-test_register.py-line22
2021-08-08 16:42:16,992-ERROR:py36:用例失败assert 2 == 0-test_register.py-line22
2021-08-08 16:43:40,090-ERROR:py36:用例失败assert 2 == 0-test_register.py-line22
2021-08-08 21:42:30,252-ERROR:py36:用例失败assert 2 == 0-test_register.py-line29
2021-08-09 01:27:49,026-ERROR:py36:用例失败assert 1 == '手机号码为空'-test_login.py-line23
2021-08-09 01:27:49,186-ERROR:py36:用例失败assert 2 == '无效的手机格式'-test_login.py-line23
2021-08-09 01:27:49,285-ERROR:py36:用例失败assert 2 == '无效的手机格式'-test_login.py-line23
2021-08-09 01:27:49,383-ERROR:py36:用例失败assert 2 == '无效的手机格式'-test_login.py-line23
2021-08-09 01:27:49,492-ERROR:py36:用例失败assert 2 == '无效的手机格式'-test_login.py-line23
2021-08-09 01:27:49,599-ERROR:py36:用例失败assert 2 == '账号信息错误'-test_login.py-line23
2021-08-09 01:27:49,708-ERROR:py36:用例失败assert 1 == '密码为空'-test_login.py-line23
2021-08-09 01:27:49,809-ERROR:py36:用例失败assert 2 == '账号信息错误'-test_login.py-line23
2021-08-09 01:27:49,925-ERROR:py36:用例失败assert 2 == 'OK'-test_login.py-line23
2021-08-09 01:31:20,384-ERROR:py36:用例失败assert '无效的手机格式' == '账号信息错误'-test_login.py-line23
2021-08-09 01:31:20,635-ERROR:py36:用例失败assert '无效的手机格式' == '账号信息错误'-test_login.py-line23
2021-08-09 01:31:20,749-ERROR:py36:用例失败assert '无效的手机格式' == 'OK'-test_login.py-line23
2021-08-09 10:53:54,319-ERROR:py36:用例失败assert '无效的手机格式' == '账号信息错误'-test_login.py-line26
2021-08-09 10:53:54,506-ERROR:py36:用例失败assert '无效的手机格式' == 'OK'-test_login.py-line26
2021-08-09 10:55:38,818-ERROR:py36:用例失败assert '账号信息错误' == 'OK'-test_login.py-line28
2021-08-09 10:56:48,987-ERROR:py36:用例失败assert '账号信息错误' == 'OK'-test_login.py-line28
2021-08-09 10:58:39,102-ERROR:py36:用例失败assert '无效的手机格式' == '账号信息错误'-test_login.py-line28
2021-08-09 10:58:39,245-ERROR:py36:用例失败assert '无效的手机格式' == 'OK'-test_login.py-line28
2021-08-09 10:59:32,902-ERROR:py36:用例失败assert '账号信息错误' == 'OK'-test_login.py-line30
2021-08-09 18:10:18,061-ERROR:py36:用例失败assert '余额必须大于0并且小于或者等于500000' == 2-test_recharge.py-line28
2021-08-09 18:10:18,341-ERROR:py36:用例失败assert '余额必须为数值型' == 2-test_recharge.py-line28
2021-08-09 18:10:18,540-ERROR:py36:用例失败assert '余额小数超过两位' == 2-test_recharge.py-line28
2021-08-09 18:10:18,753-ERROR:py36:用例失败assert '余额必须大于0并且小于或者等于500000' == 2-test_recharge.py-line28
2021-08-09 18:10:19,042-ERROR:py36:用例失败assert 'OK' == 0-test_recharge.py-line28
